basePath: /
host: localhost:8080
info:
  contact: {}
  description: A simple Todo app with Hertz + JWT + GORM
  title: Hertz Todo API
  version: "1.0"
paths:
  /auth/finished/todo:
    delete:
      description: 用户删除他的全部完成代办事件
      produces:
      - application/json
      responses:
        "204":
          description: 删除成功
          schema:
            type: string
        "500":
          description: 删除失败
          schema:
            type: string
      summary: 删除全部完成代办
      tags:
      - Todo
    put:
      description: 用户设置一个代办事件为完成状态
      parameters:
      - description: 代办id
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: 设置成功
          schema:
            type: string
        "500":
          description: 设置失败
          schema:
            type: string
      summary: 完成一个代办
      tags:
      - Todo
  /auth/finished/todos:
    get:
      description: 用户获取他的全部完成代办事件
      produces:
      - application/json
      responses:
        "200":
          description: 返回代办信息
          schema:
            items: {}
            type: array
        "500":
          description: 获取失败
          schema:
            type: string
      summary: 获取全部完成代办
      tags:
      - Todo
    put:
      description: 用户设置全部代办事件为完成状态
      produces:
      - application/json
      responses:
        "201":
          description: 设置成功
          schema:
            type: string
        "500":
          description: 设置失败
          schema:
            type: string
      summary: 完成全部代办
      tags:
      - Todo
  /auth/key/todos:
    get:
      description: 用户根据关键字获取他的代办事件
      produces:
      - application/json
      responses:
        "200":
          description: 返回代办信息
          schema:
            items: {}
            type: array
        "500":
          description: 获取失败
          schema:
            type: string
      summary: 模糊查询代办
      tags:
      - Todo
  /auth/notfinished/todo:
    delete:
      description: 用户删除他的全部未完成代办事件
      produces:
      - application/json
      responses:
        "204":
          description: 删除成功
          schema:
            type: string
        "500":
          description: 删除失败
          schema:
            type: string
      summary: 删除未完成代办
      tags:
      - Todo
    put:
      description: 用户设置一个代办事件为未完成状态
      parameters:
      - description: 代办id
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: 设置成功
          schema:
            type: string
        "500":
          description: 设置失败
          schema:
            type: string
      summary: 取消完成一个代办
      tags:
      - Todo
  /auth/notfinished/todos:
    get:
      description: 用户获取他的全部未完成代办事件
      produces:
      - application/json
      responses:
        "200":
          description: 返回代办信息
          schema:
            items: {}
            type: array
        "500":
          description: 获取失败
          schema:
            type: string
      summary: 获取全部未完成代办
      tags:
      - Todo
    put:
      description: 用户设置全部代办事件为未完成状态
      produces:
      - application/json
      responses:
        "201":
          description: 设置成功
          schema:
            type: string
        "500":
          description: 设置失败
          schema:
            type: string
      summary: 未完成全部代办
      tags:
      - Todo
  /auth/todo:
    delete:
      description: 用户删除他的一个代办事件
      produces:
      - application/json
      responses:
        "204":
          description: 删除成功
          schema:
            type: string
        "500":
          description: 删除失败
          schema:
            type: string
      summary: 删除代办
      tags:
      - Todo
  /auth/todos:
    delete:
      description: 用户删除他的全部代办事件
      produces:
      - application/json
      responses:
        "204":
          description: 删除成功
          schema:
            type: string
        "500":
          description: 删除失败
          schema:
            type: string
      summary: 删除全部代办
      tags:
      - Todo
    get:
      description: 用户获取他的全部代办事件
      produces:
      - application/json
      responses:
        "200":
          description: 返回代办信息
          schema:
            items: {}
            type: array
        "500":
          description: 获取失败
          schema:
            type: string
      summary: 获取全部代办
      tags:
      - Todo
  /auto/todo:
    post:
      description: 用户添加一个代办事件
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: 添加成功
          schema:
            type: string
        "500":
          description: 添加失败
          schema:
            type: string
      security:
      - Bearer: []
      summary: 添加代办
      tags:
      - Todo
  /register:
    post:
      description: 用户通过账号和密码创建新用户
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            type: string
        "500":
          description: 注册失败
          schema:
            type: string
      summary: 用户注册
      tags:
      - User
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
